### ISSUE TITLE
Photo of the day stuck at July 3

### ISSUE THREAD

**Issue by lucamp** [sal0max/muzei-nationalgeographic#8]
HI,
photo is stuck again like old issue https://github.com/sal0max/muzei-nationalgeographic/issues/3.

I am not sure but it seems they changed from http to https, could you please check it?

Sincerely
Luca Mina

**Comment by sal0max** [comment]
Works for me.

You're right about the change to https. Thanks for the note.
But it isn't a problem as the server redirects to the https version (301).

I suspect the problem with photos getting stuck is in Muzei itself, not this plugin.
Have you tried switching to _random mode_ and back to _photo of the day_? Does that solve the issue?

**Comment by lucamp** [comment]
Yes, switching to random mode results in two cases:
_ nothing happen (almost the time)
_ a message of retry appears (It's not a network problem as it works fine)

Now I use "Bing for Muzei"... could this means that is this plugin that cause my issue?

I have android KitKat (4.4.2)

Thanks

**Comment by lucamp** [comment]
More investigation:
I have Muzei 2.4.0 installed from f-droid (released on 16/02/2018), the issue came at July without any update.
Installing Muzei 2.6.1 from PlayStore gives the same issue and also trying 2.3.1 fdroid version. 

So apparently it started happening without any change on Muzei code

**Comment by sal0max** [comment]
There was an API change, that caused the issue.
Fixed with 77317b558dfe8ecf738b2fd1d891586381d01908

Will publish an update to the Play Store, soon.

**Comment by lucamp** [comment]
I am afraid but issue remains the same. No photo of the day or random is downloaded

**Comment by sal0max** [comment]
Did you try switching to another art source and back to ng?

**Comment by lucamp** [comment]
Sure, that was the first thing I did. Also erased the data from android "settings -> applications ".
Are there a way to debug it and see where mine stuck?

**Comment by sal0max** [comment]
Which version are you using? (Art Source | Settings | About)

**Comment by lucamp** [comment]
This morning first playstore update to 1.3.0 now received 1.3.1, but nothing changed.

Had muzei 2.4.0 from fdroid and tried again muzei 2.6.1 but same result

**Comment by sal0max** [comment]
0. Could you install this debug version? [muzei-nationalgeographic-debug.apk.zip](https://github.com/sal0max/muzei-nationalgeographic/files/2299557/muzei-nationalgeographic-debug.apk.zip) It installs next to the release build, so ne need to uninstall it.
1. Please connect your phone to the pc and run logcat.
2. Select the debug version as art source.
3. Check logcat for an entry like this one. The Tag to check for is ` Muzei_NG`:
```
08-18 15:35:05.642 23414-23657/de.msal.muzei.nationalgeographic.debug D/Muzei_NG: Artwork{title='Auto Waste', imageUri=https://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDNcYjpACw5EjdpDC9ZdYmxcmxEYblXMlGM7AKrerQRCtNN4PsDw4b7vps9aNfwE1UPql0uAuCqH-ByOiC-6gBEaAvLFv23eJn9wI_SDyGIp2KLns2ZSBelovDkK42LIHzkHD4shvfixmXG1aaZHrm1KgiFlE_o0VY-wZUK3411Iqo0/}
08-18 15:35:05.655 23414-23657/de.msal.muzei.nationalgeographic.debug I/MuzeiArtSource: Scheduling next artwork (source NationalGeographicSource) at Sun Aug 19 06:10:00 GMT+02:00 2018
```

Can you do this?

**Comment by lucamp** [comment]
There is no "Muzei_NG" in my logcat, I searched for "
Muzei".

muzei.txt was made with
`adb logcat`

muzei_vlong.txt was made with
`adb logcat -v long`

[muzei.txt](https://github.com/sal0max/muzei-nationalgeographic/files/2300130/muzei.txt)
[muzei_vlong.txt](https://github.com/sal0max/muzei-nationalgeographic/files/2300131/muzei_vlong.txt)

I also searched for "de.msal":
[muzei_de.msal.txt](https://github.com/sal0max/muzei-nationalgeographic/files/2300138/muzei_de.msal.txt)

**Comment by sal0max** [comment]
Thanks for the effort.
There are a bunch of those entries:
```
W/MuzeiArtSource(25087): Error fetching, scheduling retry, id=NationalGeographicSource
I/MuzeiArtSource(25087): Scheduling next artwork (source NationalGeographicSource) at Sun Aug 19 08:34:09 CEST 2018
```

I think this is an issue with Muzei. Check out https://github.com/berwyn/muzei-ponies/issues/5 and ultimatively https://github.com/romannurik/muzei/issues/207
Seems the new Muzei API v3 solves this issue. I didn't want to update to use it, yet, as it is still in alpha stage. But probably I will take a look into it, now.

What phone and OS are you using?

**Comment by lucamp** [comment]
Two rooted LG D620 (g2 mini) with kitkat 4.4.2.

Both smartphones have the same issue

**Comment by sal0max** [comment]
So, even if you use KitKat, is there an option in the menu where you could try to exclude Muzei + NG for Muzei from some battery/data optimizations LG might do?

I can't think of a bug in the app, as after the fix due to to API change everything works again on my OnePlus 3T, the emulator and even my old Nexus 7 with LineageOS.

**Comment by lucamp** [comment]
There is no such options in my android so I can not try that

Thanks for your efforts

**Comment by sal0max** [comment]
I'll check out API v3 when I got time. Hopefully that fixes it!
In the meantime I'm sorry I can't think of anything to do that might help.

**Comment by Xiadalei** [comment]
It seems that Muzei would love to help with the API change as Ian stated [here](https://medium.com/muzei/muzei-3-0-and-legacy-sources-8261979e2264)
For open source project you can even email support@muzei.co for help.

**Comment by sal0max** [comment]
06c7ce6b039cf549f02067bbc75bda7aacf7a9df :)
Update in the Play Store, soon.

**Comment by Xiadalei** [comment]
So has 2.0 released yet?
No update from Play Store, rolling problem maybe?

**Comment by sal0max** [comment]
I haven't pushed it, yet.
I also implemented a new feature in 2.0 for better image quality which I am testing right now.

Release is planned for this weekend. I will inform here, when it happened.
